FROM --platform=linux/x86_64 python:3.11

# 公開するポートを明示的に定義
EXPOSE 8000

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code
COPY application/ /code
RUN pip install --upgrade pip && pip install poetry
RUN poetry install

# コンテナ起動時に必ず実行したいコマンドを定義した entrypoint.sh をコピー
COPY ./containers/django/entrypoint.dev.sh /usr/local/bin/entrypoint.dev.sh
# 実行権限を付与
RUN chmod +x /usr/local/bin/entrypoint.dev.sh
ENTRYPOINT ["entrypoint.dev.sh"]

VOLUME ["/code/tmp"]

